### ISSUE TITLE
How to train it using 16 or more gpus which are in different nodes?

### ISSUE THREAD

**Issue by kaplaton** [nyu-systems/Grendel-GS#19]

**Comment by TarzanZhao** [comment]
Hi, because we are using torchrun and torchrun can support multi-node, our repository can directly train on multi-node. 

Please refer to 
[https://discuss.pytorch.org/t/how-could-we-use-torchrun-to-start-multi-node-training/138039](https://discuss.pytorch.org/t/how-could-we-use-torchrun-to-start-multi-node-training/138039)

[https://pytorch.org/docs/stable/elastic/run.html](https://pytorch.org/docs/stable/elastic/run.html)

**Comment by kaplaton** [comment]
Thank your for your reply!
